### ISSUE TITLE
Upgrade to 0.9.5-rc2

### ISSUE THREAD

**Issue by svenmueller** [tutumcloud/influxdb#58]
https://influxdb.com/blog/2015/11/13/InfluxDB-0_9_5-rc2-released.html

**Comment by geoand** [comment]
+1

I tried to use this Dockerfile to launch 0.9.5-rc2 (simply by changing the `INFLUXDB_VERSION` variable) and it did not work.
The problem seems to be that the 0.9.5-rc2 `deb` package does not create the `/opt/influxdb` directory at all, and therefore the `run.sh` cannot launch InfluxDB

**Comment by bill0ute** [comment]
+1: [v0.9.5](https://github.com/influxdb/influxdb/blob/master/CHANGELOG.md#v095-2015-11-20) the structure has changed:

The filesystem hierarchy for packages has been changed, namely:
* Binaries are now located in /usr/bin (previously /opt/influxdb)
* Configuration files are now located in /etc/influxdb (previously /etc/opt/influxdb)
* Data directories are now located in /var/lib/influxdb (previously /var/opt/influxdb)
* Scripts are now located in /usr/lib/influxdb/scripts (previously /opt/influxdb)

**Comment by hak8or** [comment]
Also +1 here too.

**Comment by gaku** [comment]
+1: we are seeing the issue with the latest influxdb image https://github.com/influxdb/influxdb/issues/4193  and it seems like it is fixed in 0.9.5.

**Comment by alappe** [comment]
Please adapt `run.sh` as @bill0ute mentioned, now that 0.9.5 is merged into master and pushed as `0.9` tag… failed on our deployments now! :-(

**Comment by tifayuki** [comment]
@alappe New images have been built.

**Comment by alappe** [comment]
Thanks, seen it… already redeploying…

**Comment by svenmueller** [comment]
please also adjust the readme (latest tag)

**Comment by bill0ute** [comment]
Awesome! Thanks.

**Comment by gaku** [comment]
Thanks for the new release!

**Comment by geoand** [comment]
Looking great! Thanks!

**Comment by svenmueller** [comment]
thanks!
