### ISSUE TITLE
Pass signals from docker to influx

### ISSUE THREAD

**Issue by homme** [tutumcloud/influxdb#84]
At the moment signals sent to the docker container are not being propagated to the `influx` process.  This is due to the fact that the `influx` is being invoked from `run.sh` which, being a shell process, by default blocks incoming signals from child processes.

**Comment by william-p** [comment]
Maybe a fix like that https://github.com/tutumcloud/influxdb/pull/78 ?

**Comment by homme** [comment]
Just like that!  Thank you.
