### ISSUE TITLE
cluster issue with JOIN on 0.12

### ISSUE THREAD

**Issue by PuKoren** [tutumcloud/influxdb#94]
it seems that influxdb ignore the join parameter and that it always fails on 0.12:

```
run: flag provided but not defined: -join
```

**Comment by MikeSchroll** [comment]
You probably are looking to post that here: https://github.com/influxdata/influxdb/issues
This repo is just a docker instance of influxdb; and is not the project itself.
This existing issue may be of help: https://github.com/influxdata/influxdb/issues/6275

**Comment by PuKoren** [comment]
Thanks, closing it then
